# Generated by Django 5.0.2 on 2026-04-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("university", "University"),
                            ("townhall", "Townhall"),
                            ("park", "Park"),
                            ("temple", "Temple"),
                            ("historical", "Historical Place"),
                            ("resort", "Resort"),
                            ("restaurant", "Restaurant"),
                            ("hotel", "Hotel"),
                            ("museum", "Museum"),
                            ("lake", "Lake"),
                            ("school", "School"),
                            ("college", "College"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.TextField()),
                ("contact", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="amenities/"),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
            ],
        ),
    ]
