# Generated by Django 5.0.2 on 2026-05-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amenity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="amenity",
            name="has_ticket",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="amenity",
            name="ticket_capacity",
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name="amenity",
            name="ticket_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=8, null=True
            ),
        ),
    ]
