# Generated by Django 5.0.2 on 2026-04-10 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("amenity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateField()),
                ("slot_time", models.TimeField(blank=True, null=True)),
                ("num_tickets", models.PositiveIntegerField(default=1)),
                (
                    "amount_per_ticket",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("payment_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("used", "Used"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("visitor_name", models.CharField(max_length=200)),
                ("visitor_phone", models.CharField(max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "amenity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_bookings",
                        to="amenity.amenity",
                    ),
                ),
            ],
        ),
    ]
