# Generated by Django 5.0.2 on 2026-05-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
